name: Ketchup test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - gha-ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.16.0"
        cache: "yarn"

    - name: Install dependencies
      run: yarn install

    - name: Run build
      run: npm run k:build

    - name: Execute tests
      run: npm run k:test:unit
