name: Ketchup test

on:
  push:
    branches: add_github_action
  pull_request:
    branches: 
     - develop
     - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 16.13.0

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run lerna bootstrap
      run: npm run lerna bootstrap

    - name: Run build
      run: npm run k:build

    - name: Execute tests
      run: npm run k:test:unit